### ISSUE TITLE
can't seem to block two spamming hosts

### ISSUE THREAD

**Issue by jusurb** [Stevie-Ray/htaccess-referral-spam-blacklist-block#22]
```
www.Get-Free-Traffic-Now.com
floating-share-buttons.com
```

![spam3](https://cloud.githubusercontent.com/assets/171747/8913943/c7bd7efa-34a4-11e5-9976-7dbef5bb8cc7.PNG)

i'm using .htaccess that i updated 2015-07-21

**Comment by jocelynduc** [comment]
Same problem here

**Comment by Stevie-Ray** [comment]
As mentioned in the README.md, this method doesn't stop the 'ghost' spammers! Because they don't really visit your website, there just using the API directly. 

You should create a segment in Google Analytics like so:

![screen shot 2015-07-27 at 20 50 08](https://cloud.githubusercontent.com/assets/5747715/8914771/6a3a32a8-34a1-11e5-86ee-315a89fd5058.png)

Exclude:

semalt.com|anticrawler.org|best-seo-offer|best-seo-solution|buttons-for-website|buttons-for-your-website|7makemoneyonline|-musicas*-gratis|kambasoft|savetubevideo|ranksonic|medispainstitute|offers.bycontext|100dollars-seo|sitevaluation|semaltmedia|success-seo|videos-for-your-business|www.Get-Free-Traffic-Now.com|maxthon.com

**Comment by jusurb** [comment]
do you have any insite on how do they get the google analytics ID for using API directly. if they just visit the page and parse the site's javascript in search for a string that contains that ID, maybe the solution would be to encode it, like back in the days email links where encoded using javascript.
i understand that this is not in your scope, but maybe you have some more knowledge about this.

**Comment by Stevie-Ray** [comment]
Well, maybe you could use a UA, and ga create, rule like this: 

``` javascript
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA'+'-'+'XXXX'+'-'+'Y', 'auto');
ga('send', 'pageview');

</script>
<!-- End Google Analytics -->
```

Unfortunately this doesn't work with the Wordpress Yoast Analytics module.
